# Generated by Django 5.0.6 on 2024-06-13 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('url_img', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('discount', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('url_img', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('description', models.TextField(blank=True)),
                ('url_img', models.CharField(max_length=100)),
                ('categories_name', models.ManyToManyField(related_name='products', to='products.categories')),
                ('promotions_name', models.ManyToManyField(related_name='products', to='products.promotions')),
            ],
        ),
    ]
