# Generated by Django 5.0.6 on 2024-06-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url_img',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
