# Generated by Django 5.0.6 on 2024-06-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_url_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='promotion_name',
            field=models.ManyToManyField(blank=True, related_name='products', to='product.promotion'),
        ),
    ]
