# Generated by Django 5.0.6 on 2024-06-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_promotion_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='promotion_name',
        ),
        migrations.AddField(
            model_name='product',
            name='category_id',
            field=models.ManyToManyField(related_name='products_id', to='product.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='promotion_id',
            field=models.ManyToManyField(blank=True, related_name='products_id', to='product.promotion'),
        ),
    ]
