# Generated by Django 5.0.6 on 2024-06-14 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_id',
            field=models.ManyToManyField(related_name='product_id', to='product.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='promotion_id',
            field=models.ManyToManyField(blank=True, related_name='product_id', to='product.promotion'),
        ),
    ]
