# Generated by Django 5.0.6 on 2024-06-21 23:36

import apps.product.models.category
import apps.product.models.product
import apps.product.models.promotion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_category_url_img_remove_product_url_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(default='default/errorCategory.webp', upload_to=apps.product.models.category.img_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default='default/errorProduct.webp', upload_to=apps.product.models.product.img_path),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='img',
            field=models.ImageField(default='default/errorPromotion.webp', upload_to=apps.product.models.promotion.img_path),
        ),
    ]
