# Generated by Django 5.0.6 on 2024-06-24 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_category_img_alter_product_img_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
    ]
