# Generated by Django 5.0.6 on 2024-06-24 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_promotion_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='original_price',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
